"""EXCEPTIONS.md -- the itemised list of what the run could not resolve.

Written from a real run, not curated. It is the honest half of the harness: a
reconciliation tool is judged on what it admits it could not do, and a demo that
shows only the match rate is showing half the number.

Orders still inside their settlement window are summarised rather than itemised.
They are not exceptions -- nobody works a payout that is not due yet -- but the
count is stated, because silently omitting 1,100 rows from a file called
EXCEPTIONS.md is the kind of omission this file exists to prevent.

Two sections come from the claims register rather than from the matcher: the claims
still open at the end of the corpus, and the ones whose filing window closed with no
recovery. The second is the most expensive list in the file -- money that was
identified, chased and then lost to a deadline -- and a file called EXCEPTIONS.md that
listed only unmatched rows would leave it out.
"""

from __future__ import annotations

from collections import Counter
from datetime import date
from decimal import Decimal
from typing import Iterable

from harness.aging import Aging
from harness.metrics import CARRIED, is_open_exception
from pipeline.claims.models import Claim, ClaimStatus
from pipeline.claims.queue import QueueView
from pipeline.matcher import BatchResult, Bucket, Verdict

TABLE_LABEL = {
    "settlement_report": "settlement",
    "bank_statement": "bank",
    "internal_ledger": "ledger",
}

ZERO = Decimal("0.00")
#: Sorts after every real deadline, so an unclocked claim lands last.
_FAR = date.max
DETAIL_KEYS = (
    "expected_fee", "charged_fee", "fee_delta", "expected_net", "settled_net",
    "net_delta", "tolerance_inr", "days_late", "settlement_sum", "bank_amount",
    "shortfall", "residual_rows", "rows_in_group", "row_net", "due_by", "message",
)


def open_exceptions(result: BatchResult) -> list[Verdict]:
    return [
        verdict
        for verdict in result.verdicts
        if verdict.bucket in (Bucket.VARIANCE, Bucket.UNMATCHED, Bucket.QUARANTINED)
        and is_open_exception(verdict.reason)
    ]


def _detail_line(verdict: Verdict) -> str:
    parts = [f"{key}={verdict.detail[key]}" for key in DETAIL_KEYS if key in verdict.detail]
    return "; ".join(parts)


def _item(verdict: Verdict) -> str:
    impact = f"₹{verdict.impact_inr}" if verdict.impact_inr != ZERO else "—"
    order = (
        f"`{verdict.order_id}`"
        if verdict.order_id and verdict.order_id != verdict.row_id
        else "—"
    )
    return (
        f"| `{verdict.row_id}` | {TABLE_LABEL[verdict.table]} | {order} "
        f"| {verdict.channel or '—'} | {impact} | {_detail_line(verdict) or '—'} |"
    )


def _batch_section(result: BatchResult, aging: Aging) -> list[str]:
    items = open_exceptions(result)
    new = [verdict for verdict in items if aging.is_new(result.batch, verdict)]
    aged = [verdict for verdict in items if not aging.is_new(result.batch, verdict)]
    carried = sum(1 for v in result.verdicts if v.reason is CARRIED)

    lines = [f"## Batch {result.batch:02d} — {len(new)} new", ""]
    notes = []
    if aged:
        oldest = max(aging.age_in_batches(result.batch, v) for v in aged)
        notes.append(
            f"{len(aged)} findings are still open from earlier batches (the oldest first "
            f"raised {oldest} batches ago) and are itemised where they were raised, not here."
        )
    if carried:
        notes.append(
            f"{carried} orders are inside their settlement window: carried forward, not queued."
        )
    if notes:
        lines += [f"*{note}*" for note in notes] + [""]
    if not new:
        lines += ["Nothing new.", ""]
        return lines

    grouped: dict[str, list[Verdict]] = {}
    for verdict in new:
        grouped.setdefault(verdict.reason.value, []).append(verdict)

    for reason in sorted(grouped, key=lambda r: (-len(grouped[r]), r)):
        rows = grouped[reason]
        total = sum((v.impact_inr for v in rows), ZERO)
        lines += [
            f"### `{reason}` — {len(rows)} row(s), ₹{total} in question",
            "",
            "| row | table | order | channel | impact | what the matcher measured |",
            "|---|---|---|---|---|---|",
        ]
        lines += [_item(verdict) for verdict in sorted(rows, key=lambda v: v.row_id)]
        lines.append("")
    return lines


def _summary(results: Iterable[BatchResult], aging: Aging) -> list[str]:
    results = list(results)
    reasons: Counter[str] = Counter()
    impact = ZERO
    for result in results:
        for verdict in open_exceptions(result):
            if aging.is_new(result.batch, verdict):
                reasons[verdict.reason.value] += 1
                impact += verdict.impact_inr

    lines = [
        "# EXCEPTIONS",
        "",
        "Generated by `make score` from a real run over all ten batches. Not curated,",
        "not filtered, and regenerated from scratch every run.",
        "",
        f"**{sum(reasons.values())} open exceptions, ₹{impact} in question.**",
        "",
        "| reason | rows |",
        "|---|---|",
    ]
    lines += [f"| `{reason}` | {count} |" for reason, count in reasons.most_common()]
    lines += [
        "",
        "Two counting rules, both aimed at not overstating the queue:",
        "",
        "- **Each finding is listed once, in the batch it was raised.** An order that goes",
        "  overdue in batch 5 and is never paid is still unmatched in batches 6 to 10 — one",
        "  problem, not six. The later batches say how many are still open instead of",
        "  relisting them.",
        "- **Impact sits on the order or the credit**, not on every settlement row that",
        "  shares it, so a variance affecting a payment and its refund is counted once.",
        "",
        "---",
        "",
    ]
    return lines


def _claim_row(claim: Claim, days: int | None) -> str:
    clock = "no configured window" if days is None else f"{days} days left"
    return (
        f"| `{claim.claim_id}` | {claim.platform} | `{claim.cause}` "
        f"| {'`' + claim.order_key + '`' if claim.order_key else '—'} "
        f"| ₹{claim.amount_inr} | {claim.status.value} "
        f"| {claim.deadline.on or '—'} | {clock} |"
    )


def _open_claims(view: QueueView) -> list[str]:
    """Claims still being chased when the corpus ends, soonest expiry first."""
    lines = [
        "## Still being chased",
        "",
        f"**{view.header}**",
        "",
        "Sorted by expiry, not by creation date. These are exceptions someone else has to",
        "pay for: they are out of the seller's hands and on a clock.",
        "",
        "| claim | platform | cause | order | amount | status | deadline | clock |",
        "|---|---|---|---|---|---|---|---|",
    ]
    lines += [_claim_row(row.claim, row.days_remaining) for row in view.rows]
    lines += [
        "",
        f"{view.unclocked_count} of these have no configured filing window in",
        "`config/thresholds.yaml`. They are shown last and carry no countdown, because",
        "inventing one would put a deadline on screen that no agreement backs.",
        "",
        "---",
        "",
    ]
    return lines


def _expired_claims(claims: list[Claim]) -> list[str]:
    """Money that was found, chased and then lost to a deadline. The worst list here."""
    expired = [claim for claim in claims if claim.status is ClaimStatus.EXPIRED]
    total = sum((claim.amount_inr for claim in expired), ZERO)
    lines = [
        "## Expired unrecovered",
        "",
        f"**{len(expired)} claims, ₹{total}.** The filing window closed and no credit ever",
        "matched them. This is the most expensive list in the file: every row here is money",
        "the system identified, chased, and then lost to a clock.",
        "",
        "| claim | platform | cause | order | amount | opened | expired on |",
        "|---|---|---|---|---|---|---|",
    ]
    lines += [
        f"| `{c.claim_id}` | {c.platform} | `{c.cause}` "
        f"| {'`' + c.order_key + '`' if c.order_key else '—'} | ₹{c.amount_inr} "
        f"| batch {c.opened_batch} | {c.deadline.on} |"
        for c in sorted(expired, key=lambda c: (c.deadline.on or _FAR, c.claim_id))
    ]
    lines += ["", "---", ""]
    return lines


def render(
    results: list[BatchResult],
    aging: Aging,
    view: QueueView | None = None,
    claims: list[Claim] | None = None,
) -> str:
    lines = _summary(results, aging)
    if view is not None:
        lines += _open_claims(view)
    if claims:
        lines += _expired_claims(claims)
    for result in results:
        lines += _batch_section(result, aging)
    return "\n".join(lines).rstrip() + "\n"
