"""EXCEPTIONS.md -- the itemised list of what the run could not resolve.

Written from a real run, not curated. It is the honest half of the harness: a
reconciliation tool is judged on what it admits it could not do, and a demo that
shows only the match rate is showing half the number.

Orders still inside their settlement window are summarised rather than itemised.
They are not exceptions -- nobody works a payout that is not due yet -- but the
count is stated, because silently omitting 1,100 rows from a file called
EXCEPTIONS.md is the kind of omission this file exists to prevent.
"""

from __future__ import annotations

from collections import Counter
from decimal import Decimal
from typing import Iterable

from harness.aging import Aging
from harness.metrics import CARRIED, is_open_exception
from pipeline.matcher import BatchResult, Bucket, Verdict

TABLE_LABEL = {
    "settlement_report": "settlement",
    "bank_statement": "bank",
    "internal_ledger": "ledger",
}

ZERO = Decimal("0.00")
DETAIL_KEYS = (
    "expected_fee", "charged_fee", "fee_delta", "expected_net", "settled_net",
    "net_delta", "tolerance_inr", "days_late", "settlement_sum", "bank_amount",
    "shortfall", "residual_rows", "rows_in_group", "row_net", "due_by", "message",
)


def open_exceptions(result: BatchResult) -> list[Verdict]:
    return [
        verdict
        for verdict in result.verdicts
        if verdict.bucket in (Bucket.VARIANCE, Bucket.UNMATCHED, Bucket.QUARANTINED)
        and is_open_exception(verdict.reason)
    ]


def _detail_line(verdict: Verdict) -> str:
    parts = [f"{key}={verdict.detail[key]}" for key in DETAIL_KEYS if key in verdict.detail]
    return "; ".join(parts)


def _item(verdict: Verdict) -> str:
    impact = f"₹{verdict.impact_inr}" if verdict.impact_inr != ZERO else "—"
    order = (
        f"`{verdict.order_id}`"
        if verdict.order_id and verdict.order_id != verdict.row_id
        else "—"
    )
    return (
        f"| `{verdict.row_id}` | {TABLE_LABEL[verdict.table]} | {order} "
        f"| {verdict.channel or '—'} | {impact} | {_detail_line(verdict) or '—'} |"
    )


def _batch_section(result: BatchResult, aging: Aging) -> list[str]:
    items = open_exceptions(result)
    new = [verdict for verdict in items if aging.is_new(result.batch, verdict)]
    aged = [verdict for verdict in items if not aging.is_new(result.batch, verdict)]
    carried = sum(1 for v in result.verdicts if v.reason is CARRIED)

    lines = [f"## Batch {result.batch:02d} — {len(new)} new", ""]
    notes = []
    if aged:
        oldest = max(aging.age_in_batches(result.batch, v) for v in aged)
        notes.append(
            f"{len(aged)} findings are still open from earlier batches (the oldest first "
            f"raised {oldest} batches ago) and are itemised where they were raised, not here."
        )
    if carried:
        notes.append(
            f"{carried} orders are inside their settlement window: carried forward, not queued."
        )
    if notes:
        lines += [f"*{note}*" for note in notes] + [""]
    if not new:
        lines += ["Nothing new.", ""]
        return lines

    grouped: dict[str, list[Verdict]] = {}
    for verdict in new:
        grouped.setdefault(verdict.reason.value, []).append(verdict)

    for reason in sorted(grouped, key=lambda r: (-len(grouped[r]), r)):
        rows = grouped[reason]
        total = sum((v.impact_inr for v in rows), ZERO)
        lines += [
            f"### `{reason}` — {len(rows)} row(s), ₹{total} in question",
            "",
            "| row | table | order | channel | impact | what the matcher measured |",
            "|---|---|---|---|---|---|",
        ]
        lines += [_item(verdict) for verdict in sorted(rows, key=lambda v: v.row_id)]
        lines.append("")
    return lines


def _summary(results: Iterable[BatchResult], aging: Aging) -> list[str]:
    results = list(results)
    reasons: Counter[str] = Counter()
    impact = ZERO
    for result in results:
        for verdict in open_exceptions(result):
            if aging.is_new(result.batch, verdict):
                reasons[verdict.reason.value] += 1
                impact += verdict.impact_inr

    lines = [
        "# EXCEPTIONS",
        "",
        "Generated by `make score` from a real run over all ten batches. Not curated,",
        "not filtered, and regenerated from scratch every run.",
        "",
        f"**{sum(reasons.values())} open exceptions, ₹{impact} in question.**",
        "",
        "| reason | rows |",
        "|---|---|",
    ]
    lines += [f"| `{reason}` | {count} |" for reason, count in reasons.most_common()]
    lines += [
        "",
        "Two counting rules, both aimed at not overstating the queue:",
        "",
        "- **Each finding is listed once, in the batch it was raised.** An order that goes",
        "  overdue in batch 5 and is never paid is still unmatched in batches 6 to 10 — one",
        "  problem, not six. The later batches say how many are still open instead of",
        "  relisting them.",
        "- **Impact sits on the order or the credit**, not on every settlement row that",
        "  shares it, so a variance affecting a payment and its refund is counted once.",
        "",
        "---",
        "",
    ]
    return lines


def render(results: list[BatchResult], aging: Aging) -> str:
    lines = _summary(results, aging)
    for result in results:
        lines += _batch_section(result, aging)
    return "\n".join(lines).rstrip() + "\n"
