import { useMemo, useState } from 'react'
import {
  Bar, BarChart, Cell, CartesianGrid, Legend, Pie, PieChart, ResponsiveContainer,
  Tooltip, XAxis, YAxis,
} from 'recharts'
import { AlertOctagon, FileWarning, ShieldOff } from 'lucide-react'
import MetricChart from '../components/MetricChart'
import StatusBadge from '../components/StatusBadge'
import { inr, pct, humanise } from '../lib/format'

const CHANNEL_COLORS = {
  amazon: '#3D4FE0', flipkart: '#1FAA59', myntra: '#F59E0B',
  offline: '#EF4444', website: '#8B5CF6',
}
const PIE_COLORS = ['#3D4FE0', '#1FAA59', '#F59E0B', '#EF4444', '#8B5CF6', '#06B6D4', '#EC4899', '#84CC16']
const AXIS = { fill: '#6B7280', fontSize: 12 }
const TOOLTIP = { contentStyle: { borderRadius: '8px', border: '1px solid #E7E7EA', fontSize: 12 } }

const TABS = [
  { id: 'takerate', label: 'Take rate' },
  { id: 'money', label: 'Money' },
  { id: 'causes', label: 'Causes' },
  { id: 'abstention', label: 'Abstention' },
  { id: 'quarantine', label: 'Quarantine' },
]

function Card({ title, subtitle, children, className = '' }) {
  return (
    <div className={`bg-white rounded-2xl border border-divider p-6 ${className}`}>
      <h2 className="text-sm font-medium text-muted uppercase tracking-wide">{title}</h2>
      {subtitle && <p className="text-xs text-muted mt-0.5 mb-3">{subtitle}</p>}
      {children}
    </div>
  )
}

export default function Reports({ weekData, allWeeks, data }) {
  const [tab, setTab] = useState('takerate')

  const moneyByWeek = useMemo(
    () => allWeeks.map((w) => ({
      name: `W${w.week}`,
      auto: w.stats.rupeesAutoResolved,
      escalated: w.stats.rupeesEscalated,
    })),
    [allWeeks]
  )

  const impactByChannel = useMemo(() => {
    const agg = {}
    for (const exc of weekData.exceptions || []) {
      if (!exc.channel) continue
      agg[exc.channel] = (agg[exc.channel] || 0) + exc.impact
    }
    return Object.entries(agg)
      .map(([channel, value]) => ({ channel, value: Math.round(value) }))
      .sort((a, b) => b.value - a.value)
  }, [weekData])

  const causeMix = useMemo(() => {
    const agg = {}
    for (const exc of weekData.exceptions || []) {
      const label = humanise(exc.hypothesis?.cause || exc.reason)
      agg[label] = (agg[label] || 0) + 1
    }
    return Object.entries(agg)
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value)
  }, [weekData])

  const quarantine = (data.quarantine || []).filter((q) => q.batch === weekData.week)
  const reporting = data.reporting || { pins: [], questions: [], registry: [] }

  return (
    <div className="flex flex-col gap-5">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
          <p className="text-xs text-muted mt-0.5">
            Ten batches, one scored run · generated by {data.generatedFrom}. Cards marked
            “this week” follow the batch selector; everything else is the whole corpus.
          </p>
        </div>
        <div className="flex items-center gap-1 bg-white border border-divider rounded-lg p-1">
          {TABS.map((t) => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-colors ${
                tab === t.id ? 'bg-gray-900 text-white' : 'text-gray-600 hover:bg-gray-50'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>
      </div>

      {tab === 'takerate' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card
            title="Effective take rate, week by week"
            subtitle="Every deduction as a percentage of gross order value — not rupees. Batch sizes grow from 59 settlement rows to 181, so an absolute fee line rises whatever the platforms do."
          >
            <MetricChart result={reporting.takeRateByBatch} height={260} />
            <p className="text-xs text-muted mt-3 leading-relaxed">
              As a percentage this line says one thing and it is the thing that matters: a
              rising line is the effective take rate climbing, which is exactly what a silent
              commission change looks like from the outside.
            </p>
          </Card>

          <Card
            title="Take rate by channel"
            subtitle="Commission, GST on commission, TCS and TDS, over gross order value"
          >
            <MetricChart result={reporting.takeRateByChannel} height={260} />
            <p className="text-xs text-muted mt-3 leading-relaxed">
              The marketplaces keep a fifth to a third of gross; the own website and the POS
              counter keep about two percent, because there the only deduction is the payment
              gateway. Commission alone, before the tax withheld on top of it:{' '}
              {(reporting.commissionShareByChannel?.points || [])
                .map((p) => `${p.label} ${p.value}%`)
                .join(', ')}.
            </p>
          </Card>
        </div>
      )}

      {tab === 'money' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <Card
            title="Auto-resolved vs escalated, per week"
            subtitle="The system automates volume and escalates value. That is the guardrails, not a limitation."
            className="lg:col-span-2 h-80 flex flex-col"
          >
            <div className="flex-1">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={moneyByWeek} margin={{ top: 4, right: 8, left: 8, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#E7E7EA" vertical={false} />
                  <XAxis dataKey="name" axisLine={false} tickLine={false} tick={AXIS} />
                  <YAxis axisLine={false} tickLine={false} tick={AXIS}
                         tickFormatter={(v) => `₹${(v / 1000).toFixed(0)}k`} />
                  <Tooltip {...TOOLTIP} formatter={(v) => inr(v, { whole: true })} />
                  <Legend wrapperStyle={{ fontSize: 11 }} />
                  <Bar dataKey="auto" name="Auto-resolved" fill="#1FAA59" radius={[4, 4, 0, 0]}
                       isAnimationActive={false} />
                  <Bar dataKey="escalated" name="Escalated" fill="#3D4FE0" radius={[4, 4, 0, 0]}
                       isAnimationActive={false} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </Card>

          <Card title="Exception impact by channel"
                subtitle={`This week only — week ${weekData.week}, ${weekData.dateRange.from} → ${weekData.dateRange.to}`}
                className="h-80 flex flex-col">
            <div className="flex-1">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={impactByChannel} layout="vertical" margin={{ left: 20, right: 12 }}>
                  <XAxis type="number" hide />
                  <YAxis type="category" dataKey="channel" axisLine={false} tickLine={false}
                         tick={{ ...AXIS, textTransform: 'capitalize' }} width={62} />
                  <Tooltip {...TOOLTIP} formatter={(v) => inr(v, { whole: true })} />
                  <Bar dataKey="value" radius={[0, 4, 4, 0]} isAnimationActive={false}>
                    {impactByChannel.map((entry) => (
                      <Cell key={entry.channel} fill={CHANNEL_COLORS[entry.channel] || '#6B7280'} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </Card>
        </div>
      )}

      {tab === 'causes' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card title={`Cause mix — week ${weekData.week}`}
                subtitle="From the model's hypothesis, constrained to the frozen enum"
                className="h-96 flex flex-col">
            <div className="flex-1">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={causeMix} dataKey="value" nameKey="name" cx="50%" cy="50%"
                       innerRadius={55} outerRadius={100} paddingAngle={2}
                       isAnimationActive={false}>
                    {causeMix.map((entry, i) => (
                      <Cell key={entry.name} fill={PIE_COLORS[i % PIE_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip {...TOOLTIP} />
                  <Legend wrapperStyle={{ fontSize: 10 }} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </Card>

          <Card title="Where each exception went" subtitle="Outcome of the deterministic rule pass">
            <div className="space-y-2 mt-2">
              {Object.entries(
                (weekData.exceptions || []).reduce((acc, e) => ({ ...acc, [e.outcome]: (acc[e.outcome] || 0) + 1 }), {})
              )
                .sort((a, b) => b[1] - a[1])
                .map(([outcome, count]) => (
                  <div key={outcome} className="flex items-center justify-between border-b border-divider py-2">
                    <span className="text-sm text-gray-800">{humanise(outcome)}</span>
                    <span className="font-bold text-gray-900">{count}</span>
                  </div>
                ))}
            </div>
            <p className="text-xs text-muted mt-4 leading-relaxed">
              Overall auto-resolution precision across the corpus is{' '}
              <span className="font-semibold text-gray-900">{pct(data.overallPrecision, 2)}</span>,
              scored against the answer key the pipeline never reads.
            </p>
          </Card>
        </div>
      )}

      {tab === 'abstention' && (
        <Card
          title="Correct abstention"
          subtitle="Two causes were held out of the corpus until late. The system had to refuse to automate them on first sight."
        >
          <div className="mt-3 space-y-3">
            {(data.abstention || []).map((entry) => (
              <div key={entry.cause} className={`rounded-xl border p-4 ${
                entry.correct ? 'border-success/30 bg-success-light/30' : 'border-danger/40 bg-danger-light/30'
              }`}>
                <div className="flex items-center gap-2 mb-2 flex-wrap">
                  {entry.correct
                    ? <ShieldOff size={15} className="text-success" />
                    : <AlertOctagon size={15} className="text-danger" />}
                  <span className="font-semibold text-gray-900 text-sm">{humanise(entry.cause)}</span>
                  <StatusBadge variant="muted">first seen in batch {entry.first_batch}</StatusBadge>
                  <StatusBadge variant={entry.correct ? 'success' : 'danger'}>
                    {entry.abstention_rate_pct}% abstention
                  </StatusBadge>
                </div>
                <p className="text-sm text-gray-700">
                  {entry.cases_on_first_sight} case(s) on first sight,{' '}
                  <strong>{entry.auto_resolved_on_first_sight} auto-resolved</strong>.
                  {' '}Across the whole corpus: {entry.total_cases} cases,{' '}
                  {entry.auto_resolved_ever} auto-resolved.
                </p>
              </div>
            ))}
          </div>
          <p className="text-xs text-muted mt-4 leading-relaxed">
            Abstention here is not a special case in the code. It falls out of the lifecycle —
            a rule that has never been induced cannot fire — and of the guardrails, which refuse
            to automate a counterparty claim or a cause on the never-auto-resolve list however
            confident a rule is.
          </p>
        </Card>
      )}

      {tab === 'quarantine' && (
        <Card
          title={`Quarantined rows — week ${weekData.week}`}
          subtitle="Malformed input is parked with a reason and counted. Never dropped, never silently skipped."
        >
          {quarantine.length === 0 ? (
            <p className="text-sm text-muted mt-3">
              No rows were refused in week {weekData.week}.
            </p>
          ) : (
            <div className="mt-3 space-y-2">
              {quarantine.map((q) => (
                <div key={q.rowId} className="flex items-start gap-3 border border-divider rounded-lg p-3">
                  <FileWarning size={15} className="text-amber mt-0.5 flex-shrink-0" />
                  <div className="min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-mono text-xs font-semibold text-gray-900">{q.rowId}</span>
                      <StatusBadge variant="amber">{humanise(q.reason)}</StatusBadge>
                      <span className="text-xs text-muted">{q.table}</span>
                    </div>
                    <p className="text-xs text-gray-700 mt-1 font-mono break-words">{q.message}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
          <p className="text-xs text-muted mt-4">
            {(data.quarantine || []).length} rows quarantined across all ten batches.
          </p>
        </Card>
      )}
    </div>
  )
}
